### ISSUE TITLE
Build issue with Java 8

### ISSUE THREAD

**Issue by hgarfer** [Concurnas/Concurnas#22]
Currently I am not able to build Concurnas using Java 8, I have tested the following Java implementations (presented with their sdkman names):
```
8.0.242-amzn
8.0.242-open
8.0.242.j9-adpt
```
it does build using `9.0.4-open`,

Stacktrace:
```
> Configure project :
Gradle version: 5.6.1

> Task :clean
> Task :generateGrammarSource

> Task :compileJava
/home/holger/projects/concurnas/Concurnas/src/runtimeCache/com/concurnas/runtimeCache/RuntimeCacheModules.java:119: error: cannot find symbol
	private static Path modStrToURI(Module mod) {
	                                ^
  symbol:   class Module
  location: class RuntimeCacheModules
/home/holger/projects/concurnas/Concurnas/src/runtime/com/concurnas/runtime/bootstrapCloner/Cloner.java:41: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
/home/holger/projects/concurnas/Concurnas/src/runtimeCache/com/concurnas/runtimeCache/RuntimeCacheModules.java:133: error: cannot find symbol
		List<Path> modulePaths = ModuleLayer.boot().modules().stream().map(a-> modStrToURI(a) ).sorted().collect(Collectors.toList());
		                         ^
  symbol:   variable ModuleLayer
  location: class RuntimeCacheModules
/home/holger/projects/concurnas/Concurnas/src/runtime/com/concurnas/runtime/bootstrapCloner/Cloner.java:218: warning: Unsafe is internal proprietary API and may be removed in a future release
	private static Unsafe unsafe;
	               ^
/home/holger/projects/concurnas/Concurnas/src/runtime/com/concurnas/runtime/bootstrapCloner/Cloner.java:221: warning: Unsafe is internal proprietary API and may be removed in a future release
			Field f = Unsafe.class.getDeclaredField("theUnsafe");
			          ^
/home/holger/projects/concurnas/Concurnas/src/runtime/com/concurnas/runtime/bootstrapCloner/Cloner.java:223: warning: Unsafe is internal proprietary API and may be removed in a future release
	        unsafe = (Unsafe) f.get(null);
	                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
4 warnings

> Task :compileJava FAILED
> Task :processResources NO-SOURCE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
3 actionable tasks: 3 executed
```

It seems java.lang.Module has been introduced in Java 9 which explains the error.

Should it be pointing to a different `Module` class?

Happy to help with this error but I am afraid I will need a bit of guidance.

**Comment by jasontatton** [comment]
Hi thanks for raising this and your other work in Contributing to Concurnas. The problem is as you have identified, the Module system was introduced in Java 9, but this isn't a thing prior to Java 8 - hence when building on java 8 this is an issue.

I don't think there is a way around this. Do you think being forced to build Concurnas on JDK 9 or above is an issue? I wouldn't expect that this is something average user would need to do. The bytecode which comes out of the build is always Java 8 compatible anyway.

I'll add an assertion to the gradle build to make the requirement more clear going forward

**Comment by hgarfer** [comment]
Understood, I don't think building the project is an issue for the average user, in the end a project is expected to run and building it is a different beast, if we are not going to build the project in Java 8 is it OK if I modify this pull request to change the `README.md` so it asks for Java 9? or do you prefer that I create a new pull request?

**Comment by jasontatton** [comment]
I think I've merged in all your PR's so far (2 of them?). I've updated the README.md. Please feel free to modify it if the build requirement of Java 9 isn't clear

**Comment by hgarfer** [comment]
Uops, my bad, not sure what I was thinking, thanks for updating the README!
